services:
  mongo:
    container_name: "mongo"
    image: "mongo"
    ports:
      - "127.0.0.1:27017:27017"
    restart: "always"
    volumes:
      - ./docker/mongo:/data/db # Persist data in development

  visualizer:
    container_name: "app"
    build:
      context: "./"
      dockerfile: "docker/Dockerfile"
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      # - DEBUG=True  # Uncomment for debug on
      # - PRODUCTION=True
      - MONGO_URI 
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REDIRECT_URI
    volumes:
      - ./:/app # Sync code changes in development
